name: wildfire-project

dependencies:
  - python=3.8
  - jupyterlab
  - ipykernel
  - ipywidgets
  - nb_conda_kernels
  - pandas
  - modin
  - numpy
  - matplotlib
  - seaborn
  - tqdm
  - requests
  - tensorflow
  - xgboost
  - catboost
  - lightgbm
  - pyspark
  - findspark
  - numba
  - pyarrow
  - pip
#  - pip:
#      - tensorflow-addons
channels:
  - conda-forge
